name: Java CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - uses: actions/checkout@v1
      - uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Assembling
        run: ./gradlew assemble --console=plain

  test:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - uses: actions/checkout@v1
      - uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Assembling
        run: ./gradlew assemble --console=plain
      - name: Testing
        run: ./gradlew check --stacktrace --console=plain

  publish:
    if: github.event_name == 'push' && (contains(github.ref, 'develop') || contains(github.ref, 'master'))
    runs-on: ubuntu-latest
    needs: [build, test]
    name: Push docker image
    steps:
      - uses: actions/checkout@v1
      - uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Push docker image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: ./gradlew pushImage

  deploy:
    if: github.event_name == 'push' && (contains(github.ref, 'develop') || contains(github.ref, 'master'))
    runs-on: ubuntu-latest
    needs: [publish]
    name: Deploy
    steps:
      - uses: actions/checkout@v1
      - uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Set env VERSION
        run: |
          echo "::set-env name=VERSION::$(./gradlew -q printVersion)"
        shell: bash
      - name: SH script for deploy develop
        if: github.event_name == 'push' && contains(github.ref, 'develop')
        uses: appleboy/ssh-action@master
        env:
          PROJECT_TAG: TRANSLATOR_IMAGE_VERSION
        with:
          username: ci
          host: ${{ secrets.DEPLOY_IP_DEVELOP }}
          key: ${{ secrets.SSH_PRIVATE }}
          envs: VERSION, PROJECT_TAG
          script: |
            echo $PROJECT_TAG=$VERSION > ~/subl/properties/$PROJECT_TAG
            sh ~/subl/start.sh

      - name: SH script for deploy master
        if: github.event_name == 'push' && contains(github.ref, 'master')
        uses: appleboy/ssh-action@master
        env:
          PROJECT_TAG: TRANSLATOR_IMAGE_VERSION
        with:
          username: ci
          host: ${{ secrets.DEPLOY_IP_MASTER }}
          key: ${{ secrets.SSH_PRIVATE }}
          envs: VERSION, PROJECT_TAG
          script: |
            echo $PROJECT_TAG=$VERSION > ~/subl/properties/$PROJECT_TAG
            sh ~/subl/start.sh